use super::*;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Reload,
    Load,
    Save,
    SaveAs,
    ZoomIn,
    ZoomOut,
    ZoomReset,
    MoveItem {
        selection: Selection,
        dx: f32,
        dy: f32,
    },
    ResizeItem {
        selection: Selection,
        handle: ResizeHandle,
        dx: f32,
        dy: f32,
    },
    ResizeBand {
        band: usize,
        dy: f32,
    },
    ResizeLayoutDivider {
        selection: Selection,
        divider: usize,
        horizontal: bool,
        delta: f32,
    },
    GeometryChanged(GeometryField, String),
    GeometryStep(GeometryField, f32),
    ItemNameChanged(String),
    TextEdited(text_editor::Action),
    FontSizeChanged(String),
    FontSizeStep(f32),
    ImageSourceChanged(String),
    BrowseImageSource,
    ImageFitChanged(ImageFit),
    HorizontalAlignChanged(HorizontalAlign),
    VerticalAlignChanged(VerticalAlign),
    FontFamilyChanged(String),
    BoldChanged(bool),
    ItalicChanged(bool),
    WordWrapChanged(bool),
    AutoHeightChanged(bool),
    PaddingChanged(PaddingField, String),
    PaddingStep(PaddingField, f32),
    BackgroundEnabled(bool),
    BackgroundColorChanged(String),
    BackgroundColorSelected(ReportColor),
    BorderEnabled(bool),
    BorderSideChanged(BorderSide, bool),
    BorderWidthChanged(String),
    BorderWidthStep(f32),
    ShapeBorderWidthChanged(String),
    ShapeBorderWidthStep(f32),
    BandHeightChanged(String),
    BandHeightStep(f32),
    BandDataSourceChanged(String),
    EqualizeLayoutChildren,
    TextColorChanged(String),
    TextColorSelected(ReportColor),
    ToggleGroup(PropertyGroup),
    FontLoaded,
    Undo,
    Redo,
    Copy,
    Paste,
    Cut,
    Delete,
    SelectAll,
    OpenContextMenu {
        selection: Option<Selection>,
        band: Option<usize>,
        position: Point,
    },
    CloseContextMenu,
    BeginCanvasInteraction {
        selection: Option<Selection>,
        band: Option<usize>,
        additive: bool,
    },
    EndCanvasInteraction,
    ToggleProperties,
    ResizeProperties(f32),
    ToggleGuides,
    DismissError,
    OpenSettings,
    CloseSettings,
    SettingsOrientationChanged(Orientation),
    SettingsMarginChanged(MarginField, String),
    SettingsMarginStep(MarginField, f32),
    SettingsFontChanged(String),
    ApplySettings,
    ToggleMenu(AppMenu),
    CloseMenu,
    OpenAbout,
    CloseAbout,
    ToggleToolbox,
    UseTool(DesignerTool),
    NewReport,
    ToggleRecentReports,
    OpenRecentReport(PathBuf),
}
