use super::*;

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Reload,
    Load,
    Save,
    SaveAs,
    Preview,
    PreviewLaunched(Result<(), String>),
    ZoomIn,
    ZoomOut,
    ZoomReset,
    MoveItem {
        selection: Selection,
        dx: f32,
        dy: f32,
    },
    ResizeItem {
        selection: Selection,
        handle: ResizeHandle,
        dx: f32,
        dy: f32,
    },
    ResizeBand {
        band: usize,
        dy: f32,
    },
    ResizeLayoutDivider {
        selection: Selection,
        divider: usize,
        horizontal: bool,
        delta: f32,
    },
    GeometryChanged(GeometryField, String),
    GeometryStep(GeometryField, f32),
    ItemNameChanged(String),
    TextEdited(text_editor::Action),
    ValueTypeChanged(String),
    QuerySourceChanged(String),
    OpenQueryFieldPicker,
    SelectQueryField(String),
    CloseQueryFieldPicker,
    OpenFunctionPicker,
    SelectFunction(String),
    CloseFunctionPicker,
    FontSizeChanged(String),
    FontSizeStep(f32),
    ImageSourceChanged(String),
    BrowseImageSource,
    ImageFitChanged(ImageFit),
    HorizontalAlignChanged(HorizontalAlign),
    VerticalAlignChanged(VerticalAlign),
    FontFamilyChanged(String),
    BoldChanged(bool),
    ItalicChanged(bool),
    UnderlineChanged(bool),
    StrikeoutChanged(bool),
    WordWrapChanged(bool),
    AutoHeightChanged(bool),
    ValueFormatDecimalChanged(String),
    ValueFormatDatePatternChanged(String),
    ValueFormatPrefixChanged(String),
    ValueFormatSuffixChanged(String),
    ValueFormatGroupingChanged(bool),
    PaddingChanged(PaddingField, String),
    PaddingStep(PaddingField, f32),
    BackgroundEnabled(bool),
    BackgroundColorChanged(String),
    BackgroundColorSelected(ReportColor),
    BorderEnabled(bool),
    BorderSideChanged(BorderSide, bool),
    BorderWidthChanged(String),
    BorderWidthStep(f32),
    ShapeBorderWidthChanged(String),
    ShapeBorderWidthStep(f32),
    BandHeightChanged(String),
    BandHeightStep(f32),
    FitActiveBandToContents,
    BandDataSourceChanged(String),
    DataHeaderRepeatChanged(bool),
    MoveBandUp(usize),
    MoveBandDown(usize),
    EqualizeLayoutChildren,
    TextColorChanged(String),
    TextColorSelected(ReportColor),
    ToggleGroup(PropertyGroup),
    FontLoaded,
    Undo,
    Redo,
    Copy,
    Paste,
    Cut,
    Delete,
    SelectAll,
    OpenContextMenu {
        selection: Option<Selection>,
        band: Option<usize>,
        position: Point,
    },
    CloseContextMenu,
    BeginCanvasInteraction {
        selection: Option<Selection>,
        band: Option<usize>,
        additive: bool,
    },
    EndCanvasInteraction,
    ToggleProperties,
    ShowSidebarTab(SidebarTab),
    ShowDataQueryTab(DataQueryTab),
    ReportParameterTypeChanged(usize, String),
    ReportParameterDefaultChanged(usize, String),
    ReportParameterRequiredChanged(usize, bool),
    NewDataSource,
    EditDataSource(usize),
    DataSourceNameChanged(String),
    DataSourcePathChanged(String),
    BrowseDataSourcePath,
    TestDataSourceConnection,
    SaveDataSource,
    CancelDataSourceEdit,
    NewDataQuery(usize),
    EditDataQuery {
        source: usize,
        query: usize,
    },
    DataQueryNameChanged(String),
    DataQuerySqlEdited(text_editor::Action),
    OpenQueryTextMenu(QueryTextTarget),
    CloseQueryTextMenu,
    CopyQueryText,
    CutQueryText,
    PasteQueryText,
    SelectAllQueryText,
    QueryTextPasted(Option<String>),
    SaveDataQuery,
    CancelDataQueryEdit,
    OpenQueryRules {
        source: usize,
        query: usize,
    },
    AddQueryFilter,
    QueryFilterFieldChanged(usize, String),
    QueryFilterOperatorChanged(usize, String),
    QueryFilterValueChanged(usize, String),
    QueryFilterCaseChanged(usize, bool),
    RemoveQueryFilter(usize),
    AddQuerySort,
    QuerySortFieldChanged(usize, String),
    QuerySortDirectionChanged(usize, String),
    MoveQuerySortUp(usize),
    MoveQuerySortDown(usize),
    RemoveQuerySort(usize),
    PreviewQueryRules,
    SaveQueryRules,
    CancelQueryRules,
    ToggleDataQueryFields {
        source: usize,
        query: usize,
    },
    ToggleDataField {
        query: String,
        field: String,
    },
    GenerateDataFields(String),
    ToggleDataTemplates(String),
    CloseDataTemplates,
    GenerateDataFieldsWithTemplate(String, usize),
    DropDataFields(usize),
    CancelDataFieldDrag,
    DroppedColumnTitleChanged(usize, String),
    DroppedColumnWidthChanged(usize, String),
    DroppedColumnAlignmentChanged(usize, HorizontalAlign),
    DroppedColumnValueTypeChanged(usize, String),
    DroppedColumnDecimalsChanged(usize, String),
    DroppedColumnDatePatternChanged(usize, String),
    DroppedColumnPrefixChanged(usize, String),
    DroppedColumnSuffixChanged(usize, String),
    DroppedColumnGroupingChanged(usize, bool),
    MoveDroppedColumnUp(usize),
    MoveDroppedColumnDown(usize),
    CenterDroppedTableChanged(bool),
    IncludeRowNumberChanged(bool),
    TableTemplateNameChanged(String),
    SaveTableTemplate,
    ApplyTableTemplate(usize),
    DeleteTableTemplate(usize),
    CreateDroppedDataFields(bool),
    CancelDataFieldDrop,
    SelectStructureBand(usize),
    ToggleStructureLayout(Selection),
    BeginStructureDrag(Selection),
    HoverStructureDrop(Selection),
    HoverStructureBand(usize),
    DropStructureItem,
    MoveEntireLayout,
    DismantleLayoutAndMoveItem,
    CancelLayoutMove,
    DismantleSelectedLayout,
    BeginStructureRename(Selection),
    BeginSelectedStructureRename,
    StructureNameChanged(String),
    CommitStructureRename,
    CancelStructureRename,
    ModifiersChanged(keyboard::Modifiers),
    CursorMoved(Point),
    ResizeProperties(f32),
    ToggleGuides,
    DismissError,
    OpenSettings,
    CloseSettings,
    SettingsOrientationChanged(Orientation),
    SettingsMarginChanged(MarginField, String),
    SettingsMarginStep(MarginField, f32),
    SettingsFontChanged(String),
    SettingsAutoCloseMessagesChanged(bool),
    ApplySettings,
    ToggleMenu(AppMenu),
    CloseMenu,
    OpenAbout,
    CloseAbout,
    ToggleToolbox,
    UseTool(DesignerTool),
    NewReport,
    ToggleRecentReports,
    OpenRecentReport(PathBuf),
}
